### ISSUE TITLE
Can not decompile Python 3.9

### ISSUE THREAD

**Issue by FugerZuer** [stehack27/Python-Decompiler#2]
Unsupported opcode: JUMP_IF_NOT_EXC_MATCH
# WARNING: Decompyle incomplete

**Comment by stehack27** [comment]
Hi, it seems a python's related problem.
Check it [here](https://docs.python.org/3/library/dis.html). 

**JUMP_IF_NOT_EXC_MATCH(target)**
```
Tests whether the second value on the stack is an exception matching TOS, and jumps if it is not. Pops two values from the stack.
```
