### ISSUE TITLE
Unsupported opcode: JUMP_IF_NOT_EXC_MATCH

### ISSUE THREAD

**Issue by NiKoCZ89** [stehack27/Python-Decompiler#3]
Unsupported opcode: JUMP_IF_NOT_EXC_MATCH

any fix?

**Comment by ahopelesshadow** [comment]
as stehack27 isnt the orig dev, and this is just a compiled version of decompiler++ i dont think were going to see this fixed, I also found several error where it prints comments say # WARNING: Decompyle incomplete
